---
# Name of the client profile to install (defaults to host name)
openvpn_client_name: "{{ inventory_hostname }}"

# VPN definitions and their clients (shared with server role)
openvpn_config: []

# Global path base for exported configs on the controller
openvpn_client_local_dir_base: "{{ inventory_dir }}/artifacts"
